// <auto-generated />
using System;
using Mentora.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mentora.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124154714_Addsubdomain")]
    partial class Addsubdomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mentora.Domain.Entities.CareerGoal", b =>
                {
                    b.Property<int>("CareerGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("career_goal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CareerGoalId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("CareerGoalId");

                    b.ToTable("career_goal", (string)null);

                    b.HasData(
                        new
                        {
                            CareerGoalId = 1,
                            Name = "Grow and Advance in My Current Field"
                        },
                        new
                        {
                            CareerGoalId = 2,
                            Name = "Explore a New Career Path"
                        },
                        new
                        {
                            CareerGoalId = 3,
                            Name = "Start My Own Business or Project"
                        },
                        new
                        {
                            CareerGoalId = 4,
                            Name = "Get Guidance on My Career Journey"
                        },
                        new
                        {
                            CareerGoalId = 5,
                            Name = "Prepare for Leadership or Management Roles"
                        },
                        new
                        {
                            CareerGoalId = 6,
                            Name = "Something Else"
                        });
                });

            modelBuilder.Entity("Mentora.Domain.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country_name");

                    b.HasKey("CountryCode");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryCode = "EG",
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryCode = "SA",
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryCode = "AE",
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryCode = "KW",
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryCode = "QA",
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryCode = "BH",
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryCode = "OM",
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryCode = "JO",
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryCode = "LB",
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryCode = "IQ",
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryCode = "SY",
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryCode = "PS",
                            CountryName = "Palestine"
                        },
                        new
                        {
                            CountryCode = "YE",
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryCode = "SD",
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryCode = "DZ",
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryCode = "MA",
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryCode = "TN",
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryCode = "LY",
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryCode = "MR",
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryCode = "DJ",
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryCode = "SO",
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryCode = "KM",
                            CountryName = "Comoros"
                        });
                });

            modelBuilder.Entity("Mentora.Domain.Entities.Domain", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomainId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("DomainId");

                    b.ToTable("domains", (string)null);

                    b.HasData(
                        new
                        {
                            DomainId = 1,
                            Description = "Building software systems and applications",
                            Name = "Software Engineering"
                        },
                        new
                        {
                            DomainId = 2,
                            Description = "Machine learning and data-driven systems",
                            Name = "AI & Data Science"
                        },
                        new
                        {
                            DomainId = 3,
                            Description = "User-centered and visual design disciplines",
                            Name = "Design"
                        },
                        new
                        {
                            DomainId = 4,
                            Description = "Product strategy, management, and business skills",
                            Name = "Product & Business"
                        });
                });

            modelBuilder.Entity("Mentora.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.LearningStyle", b =>
                {
                    b.Property<int>("LearningStyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("learning_style_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningStyleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("LearningStyleId");

                    b.ToTable("learning_style", (string)null);

                    b.HasData(
                        new
                        {
                            LearningStyleId = 1,
                            Description = "Learns best through visuals, diagrams, and examples",
                            Name = "Visual"
                        },
                        new
                        {
                            LearningStyleId = 2,
                            Description = "Learns best through listening, discussions, and explanations",
                            Name = "Auditory"
                        },
                        new
                        {
                            LearningStyleId = 3,
                            Description = "Prefers text-based materials, notes, and documentation",
                            Name = "Reading/Writing"
                        },
                        new
                        {
                            LearningStyleId = 4,
                            Description = "Learns best through hands-on practice and experimentation",
                            Name = "Kinesthetic"
                        },
                        new
                        {
                            LearningStyleId = 5,
                            Description = "Learns best by building real projects",
                            Name = "Project-Based"
                        },
                        new
                        {
                            LearningStyleId = 6,
                            Description = "Prefers structured guidance and regular mentor feedback",
                            Name = "Guided Mentorship"
                        },
                        new
                        {
                            LearningStyleId = 7,
                            Description = "Prefers independent learning at own pace",
                            Name = "Self-Paced"
                        },
                        new
                        {
                            LearningStyleId = 8,
                            Description = "Learns best through group discussions and collaboration",
                            Name = "Collaborative"
                        });
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MenteeInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int")
                        .HasColumnName("technology_id");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("int")
                        .HasColumnName("experience_level");

                    b.HasKey("UserId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("mentee_interests", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MenteeProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("bio");

                    b.Property<int?>("CareerGoalId")
                        .HasColumnType("int")
                        .HasColumnName("career_goal_id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int")
                        .HasColumnName("current_level");

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<int>("EducationStatus")
                        .HasColumnType("int")
                        .HasColumnName("education_status");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<int?>("LearningStyleId")
                        .HasColumnType("int")
                        .HasColumnName("learning_style_id");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_picture_url");

                    b.HasKey("UserId");

                    b.HasIndex("CareerGoalId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("DomainId");

                    b.HasIndex("LearningStyleId");

                    b.ToTable("mentee_profile", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MenteeSubDomain", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubDomainId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SubDomainId");

                    b.HasIndex("SubDomainId");

                    b.ToTable("MenteeSubDomains");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MentorExpertise", b =>
                {
                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mentor_id");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int")
                        .HasColumnName("technology_id");

                    b.HasKey("MentorId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("mentor_expertise", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MentorProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("PastExperience")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("past_experience");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_picture_url");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("UserId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("DomainId");

                    b.ToTable("mentor_profile", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MentorSubDomain", b =>
                {
                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubDomainId")
                        .HasColumnType("int");

                    b.HasKey("MentorId", "SubDomainId");

                    b.HasIndex("SubDomainId");

                    b.ToTable("MentorSubDomains");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.SubDomain", b =>
                {
                    b.Property<int>("SubDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subdomain_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubDomainId"));

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("SubDomainId");

                    b.HasIndex("DomainId");

                    b.ToTable("subdomain", (string)null);

                    b.HasData(
                        new
                        {
                            SubDomainId = 1,
                            DomainId = 1,
                            Name = "Backend Development"
                        },
                        new
                        {
                            SubDomainId = 2,
                            DomainId = 1,
                            Name = "Frontend Development"
                        },
                        new
                        {
                            SubDomainId = 3,
                            DomainId = 1,
                            Name = "Full Stack Development"
                        },
                        new
                        {
                            SubDomainId = 4,
                            DomainId = 1,
                            Name = "Mobile Development"
                        },
                        new
                        {
                            SubDomainId = 5,
                            DomainId = 1,
                            Name = "DevOps & Cloud"
                        },
                        new
                        {
                            SubDomainId = 6,
                            DomainId = 1,
                            Name = "System Design"
                        },
                        new
                        {
                            SubDomainId = 7,
                            DomainId = 2,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            SubDomainId = 8,
                            DomainId = 2,
                            Name = "Deep Learning"
                        },
                        new
                        {
                            SubDomainId = 9,
                            DomainId = 2,
                            Name = "Computer Vision"
                        },
                        new
                        {
                            SubDomainId = 10,
                            DomainId = 2,
                            Name = "Natural Language Processing"
                        },
                        new
                        {
                            SubDomainId = 11,
                            DomainId = 2,
                            Name = "Data Analysis"
                        },
                        new
                        {
                            SubDomainId = 12,
                            DomainId = 2,
                            Name = "Data Science"
                        },
                        new
                        {
                            SubDomainId = 13,
                            DomainId = 2,
                            Name = "Data Engineering"
                        },
                        new
                        {
                            SubDomainId = 14,
                            DomainId = 3,
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            SubDomainId = 15,
                            DomainId = 3,
                            Name = "Product Design"
                        },
                        new
                        {
                            SubDomainId = 16,
                            DomainId = 3,
                            Name = "Graphic Design"
                        },
                        new
                        {
                            SubDomainId = 17,
                            DomainId = 3,
                            Name = "Motion Design"
                        },
                        new
                        {
                            SubDomainId = 18,
                            DomainId = 3,
                            Name = "Branding"
                        },
                        new
                        {
                            SubDomainId = 19,
                            DomainId = 4,
                            Name = "Product Management"
                        },
                        new
                        {
                            SubDomainId = 20,
                            DomainId = 4,
                            Name = "Business Analysis"
                        },
                        new
                        {
                            SubDomainId = 21,
                            DomainId = 4,
                            Name = "Project Management"
                        },
                        new
                        {
                            SubDomainId = 22,
                            DomainId = 4,
                            Name = "Career Coaching"
                        },
                        new
                        {
                            SubDomainId = 23,
                            DomainId = 4,
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("Mentora.Domain.Entities.Technology", b =>
                {
                    b.Property<int>("TechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("technology_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnologyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SubDomainId")
                        .HasColumnType("int")
                        .HasColumnName("subdomain_id");

                    b.HasKey("TechnologyId");

                    b.HasIndex("SubDomainId");

                    b.ToTable("technologies", (string)null);

                    b.HasData(
                        new
                        {
                            TechnologyId = 1,
                            Name = "Node.js",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 2,
                            Name = ".NET / ASP.NET Core",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 3,
                            Name = "Spring Boot",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 4,
                            Name = "Django",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 5,
                            Name = "Flask",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 6,
                            Name = "Laravel",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 7,
                            Name = "Express.js",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 8,
                            Name = "FastAPI",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 9,
                            Name = "NestJS",
                            SubDomainId = 1
                        },
                        new
                        {
                            TechnologyId = 10,
                            Name = "HTML",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 11,
                            Name = "CSS",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 12,
                            Name = "JavaScript",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 13,
                            Name = "TypeScript",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 14,
                            Name = "React",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 15,
                            Name = "Angular",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 16,
                            Name = "Vue.js",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 17,
                            Name = "Next.js",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 18,
                            Name = "Nuxt.js",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 19,
                            Name = "SASS / SCSS",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 20,
                            Name = "Tailwind CSS",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 21,
                            Name = "Bootstrap",
                            SubDomainId = 2
                        },
                        new
                        {
                            TechnologyId = 22,
                            Name = "MERN Stack",
                            SubDomainId = 3
                        },
                        new
                        {
                            TechnologyId = 23,
                            Name = "MEAN Stack",
                            SubDomainId = 3
                        },
                        new
                        {
                            TechnologyId = 24,
                            Name = "LAMP Stack",
                            SubDomainId = 3
                        },
                        new
                        {
                            TechnologyId = 25,
                            Name = "Django + React",
                            SubDomainId = 3
                        },
                        new
                        {
                            TechnologyId = 26,
                            Name = "Next.js Full Stack",
                            SubDomainId = 3
                        },
                        new
                        {
                            TechnologyId = 27,
                            Name = "REST APIs",
                            SubDomainId = 3
                        },
                        new
                        {
                            TechnologyId = 28,
                            Name = "GraphQL",
                            SubDomainId = 3
                        },
                        new
                        {
                            TechnologyId = 29,
                            Name = "Flutter",
                            SubDomainId = 4
                        },
                        new
                        {
                            TechnologyId = 30,
                            Name = "React Native",
                            SubDomainId = 4
                        },
                        new
                        {
                            TechnologyId = 31,
                            Name = "Android (Kotlin)",
                            SubDomainId = 4
                        },
                        new
                        {
                            TechnologyId = 32,
                            Name = "Android (Java)",
                            SubDomainId = 4
                        },
                        new
                        {
                            TechnologyId = 33,
                            Name = "iOS (Swift)",
                            SubDomainId = 4
                        },
                        new
                        {
                            TechnologyId = 34,
                            Name = "Xamarin",
                            SubDomainId = 4
                        },
                        new
                        {
                            TechnologyId = 35,
                            Name = "Ionic",
                            SubDomainId = 4
                        },
                        new
                        {
                            TechnologyId = 36,
                            Name = "Docker",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 37,
                            Name = "Kubernetes",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 38,
                            Name = "AWS",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 39,
                            Name = "Azure",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 40,
                            Name = "Google Cloud Platform",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 41,
                            Name = "CI/CD Pipelines",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 42,
                            Name = "Jenkins",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 43,
                            Name = "GitHub Actions",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 44,
                            Name = "GitLab CI",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 45,
                            Name = "Terraform",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 46,
                            Name = "Ansible",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 47,
                            Name = "Nginx",
                            SubDomainId = 5
                        },
                        new
                        {
                            TechnologyId = 48,
                            Name = "High Level Design (HLD)",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 49,
                            Name = "Low Level Design (LLD)",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 50,
                            Name = "Microservices Architecture",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 51,
                            Name = "REST Architecture",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 52,
                            Name = "Event-Driven Architecture",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 53,
                            Name = "Design Patterns",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 54,
                            Name = "Scalability & Load Balancing",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 55,
                            Name = "Caching (Redis, Memcached)",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 56,
                            Name = "Message Queues (Kafka, RabbitMQ)",
                            SubDomainId = 6
                        },
                        new
                        {
                            TechnologyId = 57,
                            Name = "Python",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 58,
                            Name = "Scikit-learn",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 59,
                            Name = "TensorFlow",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 60,
                            Name = "PyTorch",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 61,
                            Name = "Keras",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 62,
                            Name = "XGBoost",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 63,
                            Name = "LightGBM",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 64,
                            Name = "CatBoost",
                            SubDomainId = 7
                        },
                        new
                        {
                            TechnologyId = 65,
                            Name = "TensorFlow",
                            SubDomainId = 8
                        },
                        new
                        {
                            TechnologyId = 66,
                            Name = "PyTorch",
                            SubDomainId = 8
                        },
                        new
                        {
                            TechnologyId = 67,
                            Name = "Keras",
                            SubDomainId = 8
                        },
                        new
                        {
                            TechnologyId = 68,
                            Name = "CNNs",
                            SubDomainId = 8
                        },
                        new
                        {
                            TechnologyId = 69,
                            Name = "RNNs",
                            SubDomainId = 8
                        },
                        new
                        {
                            TechnologyId = 70,
                            Name = "Transformers",
                            SubDomainId = 8
                        },
                        new
                        {
                            TechnologyId = 71,
                            Name = "OpenCV",
                            SubDomainId = 9
                        },
                        new
                        {
                            TechnologyId = 72,
                            Name = "TensorFlow",
                            SubDomainId = 9
                        },
                        new
                        {
                            TechnologyId = 73,
                            Name = "PyTorch",
                            SubDomainId = 9
                        },
                        new
                        {
                            TechnologyId = 74,
                            Name = "YOLO",
                            SubDomainId = 9
                        },
                        new
                        {
                            TechnologyId = 75,
                            Name = "MediaPipe",
                            SubDomainId = 9
                        },
                        new
                        {
                            TechnologyId = 76,
                            Name = "NLTK",
                            SubDomainId = 10
                        },
                        new
                        {
                            TechnologyId = 77,
                            Name = "SpaCy",
                            SubDomainId = 10
                        },
                        new
                        {
                            TechnologyId = 78,
                            Name = "Hugging Face Transformers",
                            SubDomainId = 10
                        },
                        new
                        {
                            TechnologyId = 79,
                            Name = "BERT",
                            SubDomainId = 10
                        },
                        new
                        {
                            TechnologyId = 80,
                            Name = "GPT Models",
                            SubDomainId = 10
                        },
                        new
                        {
                            TechnologyId = 81,
                            Name = "Python",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 82,
                            Name = "Pandas",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 83,
                            Name = "NumPy",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 84,
                            Name = "SQL",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 85,
                            Name = "Excel",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 86,
                            Name = "Power BI",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 87,
                            Name = "Tableau",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 88,
                            Name = "Google Sheets",
                            SubDomainId = 11
                        },
                        new
                        {
                            TechnologyId = 89,
                            Name = "Python",
                            SubDomainId = 12
                        },
                        new
                        {
                            TechnologyId = 90,
                            Name = "R",
                            SubDomainId = 12
                        },
                        new
                        {
                            TechnologyId = 91,
                            Name = "Jupyter Notebook",
                            SubDomainId = 12
                        },
                        new
                        {
                            TechnologyId = 92,
                            Name = "Matplotlib",
                            SubDomainId = 12
                        },
                        new
                        {
                            TechnologyId = 93,
                            Name = "Seaborn",
                            SubDomainId = 12
                        },
                        new
                        {
                            TechnologyId = 94,
                            Name = "SQL",
                            SubDomainId = 12
                        },
                        new
                        {
                            TechnologyId = 95,
                            Name = "Machine Learning Libraries",
                            SubDomainId = 12
                        },
                        new
                        {
                            TechnologyId = 96,
                            Name = "Apache Spark",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 97,
                            Name = "Apache Airflow",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 98,
                            Name = "Hadoop",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 99,
                            Name = "BigQuery",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 100,
                            Name = "Snowflake",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 101,
                            Name = "Redshift",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 102,
                            Name = "Kafka",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 103,
                            Name = "ETL Pipelines",
                            SubDomainId = 13
                        },
                        new
                        {
                            TechnologyId = 104,
                            Name = "Figma",
                            SubDomainId = 14
                        },
                        new
                        {
                            TechnologyId = 105,
                            Name = "Adobe XD",
                            SubDomainId = 14
                        },
                        new
                        {
                            TechnologyId = 106,
                            Name = "Sketch",
                            SubDomainId = 14
                        },
                        new
                        {
                            TechnologyId = 107,
                            Name = "InVision",
                            SubDomainId = 14
                        },
                        new
                        {
                            TechnologyId = 108,
                            Name = "Zeplin",
                            SubDomainId = 14
                        },
                        new
                        {
                            TechnologyId = 109,
                            Name = "FigJam",
                            SubDomainId = 14
                        },
                        new
                        {
                            TechnologyId = 110,
                            Name = "Figma",
                            SubDomainId = 15
                        },
                        new
                        {
                            TechnologyId = 111,
                            Name = "Adobe XD",
                            SubDomainId = 15
                        },
                        new
                        {
                            TechnologyId = 112,
                            Name = "Sketch",
                            SubDomainId = 15
                        },
                        new
                        {
                            TechnologyId = 113,
                            Name = "User Journey Mapping",
                            SubDomainId = 15
                        },
                        new
                        {
                            TechnologyId = 114,
                            Name = "Wireframing",
                            SubDomainId = 15
                        },
                        new
                        {
                            TechnologyId = 115,
                            Name = "Prototyping",
                            SubDomainId = 15
                        },
                        new
                        {
                            TechnologyId = 116,
                            Name = "Photoshop",
                            SubDomainId = 16
                        },
                        new
                        {
                            TechnologyId = 117,
                            Name = "Illustrator",
                            SubDomainId = 16
                        },
                        new
                        {
                            TechnologyId = 118,
                            Name = "InDesign",
                            SubDomainId = 16
                        },
                        new
                        {
                            TechnologyId = 119,
                            Name = "Canva",
                            SubDomainId = 16
                        },
                        new
                        {
                            TechnologyId = 120,
                            Name = "After Effects",
                            SubDomainId = 17
                        },
                        new
                        {
                            TechnologyId = 121,
                            Name = "Premiere Pro",
                            SubDomainId = 17
                        },
                        new
                        {
                            TechnologyId = 122,
                            Name = "Blender",
                            SubDomainId = 17
                        },
                        new
                        {
                            TechnologyId = 123,
                            Name = "Cinema 4D",
                            SubDomainId = 17
                        },
                        new
                        {
                            TechnologyId = 124,
                            Name = "Illustrator",
                            SubDomainId = 18
                        },
                        new
                        {
                            TechnologyId = 125,
                            Name = "Photoshop",
                            SubDomainId = 18
                        },
                        new
                        {
                            TechnologyId = 126,
                            Name = "Brand Identity Systems",
                            SubDomainId = 18
                        },
                        new
                        {
                            TechnologyId = 127,
                            Name = "Logo Design Tools",
                            SubDomainId = 18
                        },
                        new
                        {
                            TechnologyId = 128,
                            Name = "Jira",
                            SubDomainId = 19
                        },
                        new
                        {
                            TechnologyId = 129,
                            Name = "Confluence",
                            SubDomainId = 19
                        },
                        new
                        {
                            TechnologyId = 130,
                            Name = "Notion",
                            SubDomainId = 19
                        },
                        new
                        {
                            TechnologyId = 131,
                            Name = "Trello",
                            SubDomainId = 19
                        },
                        new
                        {
                            TechnologyId = 132,
                            Name = "Miro",
                            SubDomainId = 19
                        },
                        new
                        {
                            TechnologyId = 133,
                            Name = "Product Roadmaps",
                            SubDomainId = 19
                        },
                        new
                        {
                            TechnologyId = 134,
                            Name = "OKRs",
                            SubDomainId = 19
                        },
                        new
                        {
                            TechnologyId = 135,
                            Name = "Excel",
                            SubDomainId = 20
                        },
                        new
                        {
                            TechnologyId = 136,
                            Name = "Power BI",
                            SubDomainId = 20
                        },
                        new
                        {
                            TechnologyId = 137,
                            Name = "Tableau",
                            SubDomainId = 20
                        },
                        new
                        {
                            TechnologyId = 138,
                            Name = "SQL",
                            SubDomainId = 20
                        },
                        new
                        {
                            TechnologyId = 139,
                            Name = "BPMN",
                            SubDomainId = 20
                        },
                        new
                        {
                            TechnologyId = 140,
                            Name = "SWOT Analysis",
                            SubDomainId = 20
                        },
                        new
                        {
                            TechnologyId = 141,
                            Name = "Jira",
                            SubDomainId = 21
                        },
                        new
                        {
                            TechnologyId = 142,
                            Name = "Trello",
                            SubDomainId = 21
                        },
                        new
                        {
                            TechnologyId = 143,
                            Name = "Asana",
                            SubDomainId = 21
                        },
                        new
                        {
                            TechnologyId = 144,
                            Name = "Monday.com",
                            SubDomainId = 21
                        },
                        new
                        {
                            TechnologyId = 145,
                            Name = "ClickUp",
                            SubDomainId = 21
                        },
                        new
                        {
                            TechnologyId = 146,
                            Name = "Resume Review Tools",
                            SubDomainId = 22
                        },
                        new
                        {
                            TechnologyId = 147,
                            Name = "Interview Preparation Frameworks",
                            SubDomainId = 22
                        },
                        new
                        {
                            TechnologyId = 148,
                            Name = "LinkedIn Optimization",
                            SubDomainId = 22
                        },
                        new
                        {
                            TechnologyId = 149,
                            Name = "Career Planning Models",
                            SubDomainId = 22
                        },
                        new
                        {
                            TechnologyId = 150,
                            Name = "Lean Canvas",
                            SubDomainId = 23
                        },
                        new
                        {
                            TechnologyId = 151,
                            Name = "Business Model Canvas",
                            SubDomainId = 23
                        },
                        new
                        {
                            TechnologyId = 152,
                            Name = "Pitch Deck Tools",
                            SubDomainId = 23
                        },
                        new
                        {
                            TechnologyId = 153,
                            Name = "Market Research Tools",
                            SubDomainId = 23
                        },
                        new
                        {
                            TechnologyId = 154,
                            Name = "Financial Modeling",
                            SubDomainId = 23
                        });
                });

            modelBuilder.Entity("Mentora.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MenteeInterest", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.Technology", "Technology")
                        .WithMany("MenteeInterests")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Domain.Entities.MenteeProfile", "MenteeProfile")
                        .WithMany("MenteeInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenteeProfile");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MenteeProfile", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.CareerGoal", "CareerGoal")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("CareerGoalId");

                    b.HasOne("Mentora.Domain.Entities.Country", "Country")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("CountryCode");

                    b.HasOne("Mentora.Domain.Entities.Domain", "Domain")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Domain.Entities.LearningStyle", "LearningStyle")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("LearningStyleId");

                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithOne("MenteeProfile")
                        .HasForeignKey("Mentora.Domain.Entities.MenteeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerGoal");

                    b.Navigation("Country");

                    b.Navigation("Domain");

                    b.Navigation("LearningStyle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MenteeSubDomain", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.SubDomain", "SubDomain")
                        .WithMany()
                        .HasForeignKey("SubDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Domain.Entities.MenteeProfile", "MenteeProfile")
                        .WithMany("MenteeSubDomains")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenteeProfile");

                    b.Navigation("SubDomain");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MentorExpertise", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.MentorProfile", "MentorProfile")
                        .WithMany("MentorExpertises")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Domain.Entities.Technology", "Technology")
                        .WithMany("MentorExpertises")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MentorProfile");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MentorProfile", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.Country", "Country")
                        .WithMany("MentorProfiles")
                        .HasForeignKey("CountryCode");

                    b.HasOne("Mentora.Domain.Entities.Domain", "Domain")
                        .WithMany("MentorProfiles")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithOne("MentorProfile")
                        .HasForeignKey("Mentora.Domain.Entities.MentorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Domain");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MentorSubDomain", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.MentorProfile", "MentorProfile")
                        .WithMany("MentorSubDomains")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Domain.Entities.SubDomain", "SubDomain")
                        .WithMany()
                        .HasForeignKey("SubDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MentorProfile");

                    b.Navigation("SubDomain");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.SubDomain", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.Domain", "Domain")
                        .WithMany("SubDomains")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.Technology", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.SubDomain", "SubDomain")
                        .WithMany("Technologies")
                        .HasForeignKey("SubDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDomain");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.CareerGoal", b =>
                {
                    b.Navigation("MenteeProfiles");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.Country", b =>
                {
                    b.Navigation("MenteeProfiles");

                    b.Navigation("MentorProfiles");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.Domain", b =>
                {
                    b.Navigation("MenteeProfiles");

                    b.Navigation("MentorProfiles");

                    b.Navigation("SubDomains");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.LearningStyle", b =>
                {
                    b.Navigation("MenteeProfiles");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MenteeProfile", b =>
                {
                    b.Navigation("MenteeInterests");

                    b.Navigation("MenteeSubDomains");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.MentorProfile", b =>
                {
                    b.Navigation("MentorExpertises");

                    b.Navigation("MentorSubDomains");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.SubDomain", b =>
                {
                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.Technology", b =>
                {
                    b.Navigation("MenteeInterests");

                    b.Navigation("MentorExpertises");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.User", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("MenteeProfile");

                    b.Navigation("MentorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
