// <auto-generated />
using System;
using Mentora.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mentora.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119080755_AddRefreshTokenTable")]
    partial class AddRefreshTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareerGoal", b =>
                {
                    b.Property<int>("CareerGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("career_goal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CareerGoalId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("CareerGoalId");

                    b.ToTable("career_goal", (string)null);
                });

            modelBuilder.Entity("Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country_name");

                    b.HasKey("CountryCode");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Domains", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomainId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("DomainId");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("LearningStyle", b =>
                {
                    b.Property<int>("LearningStyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("learning_style_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningStyleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("LearningStyleId");

                    b.ToTable("learning_style", (string)null);
                });

            modelBuilder.Entity("MenteeInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int")
                        .HasColumnName("technology_id");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("int")
                        .HasColumnName("experience_level");

                    b.HasKey("UserId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("mentee_interests", (string)null);
                });

            modelBuilder.Entity("MenteeProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("bio");

                    b.Property<int?>("CareerGoalId")
                        .HasColumnType("int")
                        .HasColumnName("career_goal_id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int")
                        .HasColumnName("current_level");

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<int>("EducationStatus")
                        .HasColumnType("int")
                        .HasColumnName("education_status");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<int?>("LearningStyleId")
                        .HasColumnType("int")
                        .HasColumnName("learning_style_id");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_picture_url");

                    b.HasKey("UserId");

                    b.HasIndex("CareerGoalId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("DomainId");

                    b.HasIndex("LearningStyleId");

                    b.ToTable("mentee_profile", (string)null);
                });

            modelBuilder.Entity("MentorExpertise", b =>
                {
                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mentor_id");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int")
                        .HasColumnName("technology_id");

                    b.HasKey("MentorId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("mentor_expertise", (string)null);
                });

            modelBuilder.Entity("MentorProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("PastExperience")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("past_experience");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("UserId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("DomainId");

                    b.ToTable("mentor_profile", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Mentora.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SubDomain", b =>
                {
                    b.Property<int>("SubDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subdomain_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubDomainId"));

                    b.Property<int>("DomainId")
                        .HasColumnType("int")
                        .HasColumnName("domain_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("SubDomainId");

                    b.HasIndex("DomainId");

                    b.ToTable("subdomain", (string)null);
                });

            modelBuilder.Entity("Technology", b =>
                {
                    b.Property<int>("TechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("technology_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnologyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SubDomainId")
                        .HasColumnType("int")
                        .HasColumnName("subdomain_id");

                    b.HasKey("TechnologyId");

                    b.HasIndex("SubDomainId");

                    b.ToTable("technologies", (string)null);
                });

            modelBuilder.Entity("MenteeInterest", b =>
                {
                    b.HasOne("Technology", "Technology")
                        .WithMany("MenteeInterests")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MenteeProfile", "MenteeProfile")
                        .WithMany("MenteeInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenteeProfile");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("MenteeProfile", b =>
                {
                    b.HasOne("CareerGoal", "CareerGoal")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("CareerGoalId");

                    b.HasOne("Country", "Country")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("CountryCode");

                    b.HasOne("Domains", "Domain")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningStyle", "LearningStyle")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("LearningStyleId");

                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithOne("MenteeProfile")
                        .HasForeignKey("MenteeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerGoal");

                    b.Navigation("Country");

                    b.Navigation("Domain");

                    b.Navigation("LearningStyle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentorExpertise", b =>
                {
                    b.HasOne("MentorProfile", "MentorProfile")
                        .WithMany("MentorExpertises")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Technology", "Technology")
                        .WithMany("MentorExpertises")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MentorProfile");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("MentorProfile", b =>
                {
                    b.HasOne("Country", "Country")
                        .WithMany("MentorProfiles")
                        .HasForeignKey("CountryCode");

                    b.HasOne("Domains", "Domain")
                        .WithMany("MentorProfiles")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithOne("MentorProfile")
                        .HasForeignKey("MentorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Domain");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Mentora.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SubDomain", b =>
                {
                    b.HasOne("Domains", "Domain")
                        .WithMany("SubDomains")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Technology", b =>
                {
                    b.HasOne("SubDomain", "SubDomain")
                        .WithMany("Technologies")
                        .HasForeignKey("SubDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDomain");
                });

            modelBuilder.Entity("CareerGoal", b =>
                {
                    b.Navigation("MenteeProfiles");
                });

            modelBuilder.Entity("Country", b =>
                {
                    b.Navigation("MenteeProfiles");

                    b.Navigation("MentorProfiles");
                });

            modelBuilder.Entity("Domains", b =>
                {
                    b.Navigation("MenteeProfiles");

                    b.Navigation("MentorProfiles");

                    b.Navigation("SubDomains");
                });

            modelBuilder.Entity("LearningStyle", b =>
                {
                    b.Navigation("MenteeProfiles");
                });

            modelBuilder.Entity("MenteeProfile", b =>
                {
                    b.Navigation("MenteeInterests");
                });

            modelBuilder.Entity("MentorProfile", b =>
                {
                    b.Navigation("MentorExpertises");
                });

            modelBuilder.Entity("Mentora.Domain.Entities.User", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("MenteeProfile");

                    b.Navigation("MentorProfile");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SubDomain", b =>
                {
                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Technology", b =>
                {
                    b.Navigation("MenteeInterests");

                    b.Navigation("MentorExpertises");
                });
#pragma warning restore 612, 618
        }
    }
}
